### ISSUE TITLE
Есть баг, не работает на prestashop 1.6

### ISSUE THREAD

**Issue by cosc** [Cassiopeja/russianpostcarrier#1]
В файле russianpostcarrier/models/RussianPost.php на строчке 48 выдается следующая ошибка: "Call to a member function execute() on a non-object"

**Comment by romeo143** [comment]
Я тоже заметил

**Comment by qant** [comment]
Поменяйте в этом файле в разных местах

RussianPost::$db-> на Db::getInstance()->

**Comment by Cassiopeja** [comment]
Решено в #2
